# Generated by Django 5.0.6 on 2024-05-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="url",
            index=models.Index(fields=["created_at"], name="urls_created_71be6f_idx"),
        ),
        migrations.AddIndex(
            model_name="url",
            index=models.Index(fields=["user_email"], name="urls_user_em_f4907d_idx"),
        ),
        migrations.AlterModelTable(
            name="url",
            table="urls",
        ),
    ]
